version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"

  deposit_service:
    image: deposit_service:latest
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - postgres
