// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: dto/proto/deposit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DepositClient is the client API for Deposit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepositClient interface {
	PeformDepositAction(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type depositClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositClient(cc grpc.ClientConnInterface) DepositClient {
	return &depositClient{cc}
}

func (c *depositClient) PeformDepositAction(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Deposit/PeformDepositAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositServer is the server API for Deposit service.
// All implementations must embed UnimplementedDepositServer
// for forward compatibility
type DepositServer interface {
	PeformDepositAction(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDepositServer()
}

// UnimplementedDepositServer must be embedded to have forward compatible implementations.
type UnimplementedDepositServer struct {
}

func (UnimplementedDepositServer) PeformDepositAction(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeformDepositAction not implemented")
}
func (UnimplementedDepositServer) mustEmbedUnimplementedDepositServer() {}

// UnsafeDepositServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositServer will
// result in compilation errors.
type UnsafeDepositServer interface {
	mustEmbedUnimplementedDepositServer()
}

func RegisterDepositServer(s grpc.ServiceRegistrar, srv DepositServer) {
	s.RegisterService(&Deposit_ServiceDesc, srv)
}

func _Deposit_PeformDepositAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServer).PeformDepositAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Deposit/PeformDepositAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServer).PeformDepositAction(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Deposit_ServiceDesc is the grpc.ServiceDesc for Deposit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deposit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Deposit",
	HandlerType: (*DepositServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PeformDepositAction",
			Handler:    _Deposit_PeformDepositAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dto/proto/deposit.proto",
}
